application: webservices 
version: 1
runtime: go117
api_version: go1

builds:
  - env:
      - CGO_ENABLED=1
    goarch:
      - amd64
    goos:
      #- linux
      #- darwin
      - windows

handlers:
- url: /.*
  script: _go_app