name: Build GO app and push to Azure

on:
  push:
    branches: [main]

jobs:

  builds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up GO
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Build
      run: go build -o build/go-app.exe -v

    - name: 'Deploy to Azure WebApp'
      uses: Azure/webapps-deploy@v2
      with:
        app-name: Admixer
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        package: build/